package com.youns03.highlightpro;

import android.app.Activity;
import android.graphics.*;
import android.net.Uri;
import android.os.Bundle;
import android.view.*;
import android.widget.Toast;
import java.util.*;

public class MainActivity extends Activity {
    ReaderView view; NativeAudioEngine audio;
    @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(Color.rgb(9,17,34));audio=new NativeAudioEngine(this);view=new ReaderView();audio.setListener(new NativeAudioEngine.Listener(){public void onPosition(float seconds,boolean isPlaying){runOnUiThread(()->{view.time=seconds;view.playing=isPlaying;view.invalidate();});}public void onEnded(){runOnUiThread(()->{view.playing=false;view.time=activeDuration();view.invalidate();});}});setContentView(view);}
    float activeDuration(){return view!=null&&view.active!=null?view.active.duration:0;}
    @Override public void onBackPressed(){if(view.reader){stopAudio();view.reader=false;view.invalidate();}else super.onBackPressed();}
    @Override protected void onDestroy(){if(audio!=null)audio.release();super.onDestroy();}
    void stopAudio(){audio.stop();if(view!=null)view.playing=false;}

    final class ReaderView extends View {
        final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); final List<LessonRepository.Lesson> lessons;
        LessonRepository.Lesson active; boolean reader=false,dark=true,showArabic=true,playing=false; float time=0; int tab=0; float speed=1f;
        final int pink=Color.rgb(244,114,142),teal=Color.rgb(45,212,191),bg=Color.rgb(9,17,34);
        ReaderView(){super(MainActivity.this);lessons=NativeLessonStore.loadMerged(MainActivity.this,LessonRepository.load(MainActivity.this));if(!lessons.isEmpty())active=lessons.get(0);dark=getPreferences(0).getBoolean("dark",true);showArabic=getPreferences(0).getBoolean("arabic",true);loadActiveAudio();}
        void loadActiveAudio(){if(active==null)return;Uri uri=NativeLessonStore.audioUri(MainActivity.this,active.id);audio.load(uri);time=0;playing=false;}
        void text(Canvas c,String s,float x,float y,float size,int color,boolean rtl){p.setTypeface(Typeface.create("sans",Typeface.NORMAL));p.setTextSize(size);p.setColor(color);p.setTextAlign(rtl?Paint.Align.RIGHT:Paint.Align.LEFT);c.drawText(s,x,y,p);}
        void bold(Canvas c,String s,float x,float y,float size,int color,boolean rtl){p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextSize(size);p.setColor(color);p.setTextAlign(rtl?Paint.Align.RIGHT:Paint.Align.LEFT);c.drawText(s,x,y,p);}
        void round(Canvas c,float l,float t,float r,float b,int color,float rad){p.setColor(color);c.drawRoundRect(l,t,r,b,rad,rad,p);}
        @Override protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();c.drawColor(dark?bg:Color.rgb(248,250,252));if(reader)drawReader(c,w,h);else drawLibrary(c,w,h);}
        void header(Canvas c,int w,String title){bold(c,title,w-24,46,22,dark?Color.WHITE:0xff0f172a,true);text(c,"تعلم الفرنسية بالصوت",w-24,73,12,dark?0xff94a3b8:0xff64748b,true);}
        void drawLibrary(Canvas c,int w,int h){header(c,w,tab==2?"الإحصائيات":tab==4?"الإعدادات":"مكتبتي");if(tab==2){drawStats(c,w,h);return;}if(tab==4){drawSettings(c,w,h);return;}int y=108;bold(c,"الدروس المتاحة دون إنترنت",w-24,y,17,dark?Color.WHITE:0xff0f172a,true);y+=28;for(int i=0;i<lessons.size();i++){LessonRepository.Lesson l=lessons.get(i);round(c,18,y,w-18,y+92,dark?0xff111c31:Color.WHITE,20);round(c,w-68,y+18,w-38,y+48,pink,15);bold(c,"FR",w-53,y+39,10,Color.WHITE,false);bold(c,l.title,w-84,y+30,16,dark?Color.WHITE:0xff0f172a,true);text(c,l.arabicTitle,w-84,y+54,13,dark?0xffcbd5e1:0xff475569,true);text(c,l.level+"   "+l.sentences.size()+" جمل",w-84,y+77,11,dark?0xff94a3b8:0xff64748b,true);y+=105;}drawNav(c,w,h);}
        void drawNav(Canvas c,int w,int h){round(c,0,h-72,w,h,dark?0xff0f172a:Color.WHITE,0);String[] labels={"المكتبة","الإحصائيات","الإعدادات"};int selected=tab==0?0:tab==2?1:2;for(int i=0;i<3;i++){float x=w-(i+.5f)*w/3f;if(selected==i)round(c,x-29,h-59,x+29,h-53,pink,4);text(c,labels[i],x,h-25,10,selected==i?pink:(dark?0xff94a3b8:0xff64748b),true);}}
        void drawStats(Canvas c,int w,int h){int color=dark?Color.WHITE:0xff0f172a;bold(c,"إحصائيات التعلم",w-24,120,20,color,true);text(c,"الدروس المحفوظة",w-24,175,14,dark?0xffcbd5e1:0xff475569,true);bold(c,String.valueOf(lessons.size()),w-24,210,38,pink,true);text(c,"جميع الدروس الافتراضية محفوظة محلياً",w-24,255,13,dark?0xff94a3b8:0xff64748b,true);drawNav(c,w,h);}
        void drawSettings(Canvas c,int w,int h){int color=dark?Color.WHITE:0xff0f172a;bold(c,"الإعدادات",w-24,120,22,color,true);round(c,18,145,w-18,214,dark?0xff111c31:Color.WHITE,18);text(c,"الوضع الداكن",w-40,173,15,color,true);text(c,dark?"مفعل":"غير مفعل",w-40,196,12,pink,true);round(c,30,166,60,194,dark?teal:0xffcbd5e1,14);round(c,dark?45:31,169,dark?57:43,191,Color.WHITE,12);round(c,18,230,w-18,302,dark?0xff111c31:Color.WHITE,18);text(c,"الترجمة العربية",w-40,260,15,color,true);text(c,showArabic?"مفعلة":"متوقفة",w-40,284,12,pink,true);drawNav(c,w,h);}
        void drawReader(Canvas c,int w,int h){int color=dark?Color.WHITE:0xff0f172a;bold(c,"‹",24,48,34,pink,false);bold(c,active.title,w-24,46,19,color,true);text(c,active.level+"  •  "+(audio.hasAudio()?"صوت محلي متزامن":"لا يوجد صوت محفوظ"),w-24,72,11,dark?0xff94a3b8:0xff64748b,true);round(c,18,91,w-18,h-144,dark?0xff0f1a2d:Color.WHITE,24);int y=140;for(LessonRepository.Sentence s:active.sentences){boolean as=time>=s.start&&time<=s.end+.1f;if(as)round(c,28,y-27,w-28,y+activeTextHeight(s.french)+(showArabic?44:8),dark?0xff243047:0xffffeef2,16);drawWords(c,s,w-42,y,color);y+=activeTextHeight(s.french)+(showArabic?56:27);}round(c,18,h-128,w-18,h-84,dark?0xff111c31:0xffffe4e9,15);bold(c,playing?"❚❚":"▶",32,h-100,17,pink,false);text(c,audio.hasAudio()?"صوت محلي — التوقيت من موضع MediaPlayer":"Android TTS كامل الدرس — غير متزامن مع التوقيتات",w-42,h-104,11,audio.hasAudio()?teal:pink,true);text(c,String.format(Locale.US,"%.2fs / %.2fs",time,active.duration),w/2,h-88,11,dark?0xffcbd5e1:0xff475569,false);text(c,"سرعة "+String.format(Locale.US,"%.1fx",speed),w-42,h-72,11,dark?0xffcbd5e1:0xff475569,true);}
        int activeTextHeight(String s){return 62+Math.max(0,(s.length()/38))*24;}
        void drawWords(Canvas c,LessonRepository.Sentence s,float right,float y,int color){float x=right;p.setTextSize(20);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));String[] ws=s.french.split(" ");for(int i=ws.length-1;i>=0;i--){String word=ws[i];float ww=p.measureText(word)+9;LessonRepository.Word timing=i<s.words.size()?s.words.get(i):null;boolean on=timing!=null&&time>=timing.start&&time<=timing.end;if(on)round(c,x-ww,y-22,x+3,y+5,0xffffb4c2,5);text(c,word,x,y,20,on?0xff0f172a:color,false);x-=ww;}if(showArabic)text(c,s.arabic,right,y+32,14,dark?0xffcbd5e1:0xff475569,true);}
        @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY();int w=getWidth(),h=getHeight();if(reader){if(y<75&&x<90){stopAudio();reader=false;invalidate();return true;}if(y>h-140&&y<h-80){if(audio.hasAudio()){if(playing)audio.pause();else audio.play();}else{speakFullLesson();Toast.makeText(MainActivity.this,"Android TTS لا يوفر word-boundaries موثوقة؛ التظليل الزمني غير منسوب إليه",Toast.LENGTH_LONG).show();}return true;}if(y>h-82&&x<180){speed=speed>=1.5f?.5f:speed+.25f;audio.setSpeed(speed);invalidate();return true;}if(y>100&&y<h-150){seekFromCanvas(x,y);return true;}return true;}if(y>h-80){int slot=Math.min(2,Math.max(0,(int)(x/(w/3))));tab=slot==0?0:slot==1?2:4;invalidate();return true;}if(tab==4&&y>140&&y<220){dark=!dark;getPreferences(0).edit().putBoolean("dark",dark).apply();invalidate();return true;}if(tab==4&&y>225&&y<310){showArabic=!showArabic;getPreferences(0).edit().putBoolean("arabic",showArabic).apply();invalidate();return true;}if(tab==0){int index=(int)((y-108)/105);if(index>=0&&index<lessons.size()){active=lessons.get(index);reader=true;loadActiveAudio();invalidate();}}return true;}
        void seekFromCanvas(float x,float targetY){int y=140;for(LessonRepository.Sentence s:active.sentences){int height=activeTextHeight(s.french)+(showArabic?56:27);if(targetY>=y-27&&targetY<=y+height){p.setTextSize(20);float right=getWidth()-42;String[] ws=s.french.split(" ");for(int i=ws.length-1;i>=0;i--){float ww=p.measureText(ws[i])+9;float left=right-ww;if(x>=left&&x<=right&&i<s.words.size()){time=s.words.get(i).start;audio.seek(time);invalidate();return;}right=left;}audio.seek(s.start);time=s.start;invalidate();return;}y+=height;}}
        void speakFullLesson(){List<String> text=new ArrayList<>();for(LessonRepository.Sentence s:active.sentences)text.add(s.french);audio.speakLesson(text,speed);playing=true;invalidate();}
    }
}
